dist: bionic

language: node_js

node_js:
  - 12

env:
  global:
    - DEV_SERVER_ADDRESS=https://api.cypherpunks.co.uk/api/v1
    - PROD_SERVER_ADDRESS=https://api.cypherpunks.co.uk/api/v1

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 1

before_install:
  - pyenv global 3.7
  - pip3 install --quiet awscli
  - aws --version
  - yarn global add serverless

install:
  - yarn install --production=false

deploy:
  - provider: script
    script: >-
      REACT_APP_SERVER_ADDRESS=$DEV_SERVER_ADDRESS yarn build;
      sls -v deploy;
      sls -v syncToS3;
      sls -v invalidateCloudFrontCache;
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: >-
      REACT_APP_SERVER_ADDRESS=$PROD_SERVER_ADDRESS yarn build;
      sls -v -s prod deploy;
      sls -v -s prod syncToS3;
      sls -v -s prod invalidateCloudFrontCache;
    skip_cleanup: true
    on:
      branch: master
